version: '3.8'

services:
  client:
    build:
      context: ./app/ITAssetManagement/client/it-asset-management-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  api:
    build:
      context: ./app/ITAssetManagement/api/VCVAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

  media:
    build:
      context: ./app/MediaService
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - ASPNETCORE_URLS=http://+:6000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
