services:
  client:
    build:
      context: ../apps/ITAssetManagement/client/it-asset-management-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  api:
    build:
      context: ../apps/ITAssetManagement/api/VCV_API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - app-network

  media:
    build:
      context: ../apps/MediaService/MediaService
      dockerfile: Dockerfile
    ports:
      - "5100:5100"
    environment:
      - ASPNETCORE_URLS=http://+:5100
    networks:
      - app-network

networks:
  app-network: