FROM mcr.microsoft.com/dotnet/aspnet:8.0

RUN apt-get update && \
    apt-get install -y \
    libreoffice libreoffice-calc libreoffice-writer \
    fontconfig fonts-dejavu \
    libxrender1 libfontconfig1 libxext6 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./fonts /usr/share/fonts/truetype/custom
RUN fc-cache -f -v